# Generated by Django 4.2.6 on 2023-10-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='med_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compound_name', models.CharField(max_length=225)),
                ('product_name', models.CharField(max_length=225)),
                ('product_id', models.IntegerField()),
                ('age_restriction', models.IntegerField(blank=True, null=True)),
                ('age_restriction_type', models.CharField(blank=True, max_length=225)),
                ('age_direction', models.CharField(blank=True, max_length=225)),
                ('contraindicated', models.ManyToManyField(blank=True, related_name='contradicated', to='searchmed.med_list')),
            ],
        ),
    ]
