# Generated by Django 4.2.5 on 2023-10-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Med',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compound_name', models.CharField(blank=True, max_length=225, null=True)),
                ('compound_code', models.CharField(blank=True, max_length=225, null=True)),
                ('product_code', models.IntegerField(blank=True, null=True)),
                ('product_name', models.CharField(blank=True, max_length=225, null=True)),
                ('company_name', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'med',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medcontraindication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contraindicated_info', models.CharField(blank=True, max_length=225, null=True)),
                ('notification_no', models.CharField(blank=True, max_length=50, null=True)),
                ('notification_date', models.DateField(blank=True, null=True)),
                ('detail_info', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'medcontraindication',
                'managed': False,
            },
        ),
    ]
